### ISSUE TITLE
[Connect] tc-includes shouldn't include any styles only mixins and variables

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/tc-ui#24]
https://github.com/appirio-tech/tc-ui/blob/feature/connectv2/src/styles/_tc-includes.scss should only include mixins and variables which are not outputted to the final CSS file but can be used only during SCSS compiling time.

The reason for that is that `_tc-includes.scss` is included multiple times in applications which use it, and every time it's included if there are any CSS styles they will be included in the output CSS file again and again. At the end it will lead to growing output CSS file, will increase loading time, processing CSS file time and could lead to slowness in browsers, see https://github.com/appirio-tech/connect-app/issues/2587 for example.

Any styles which has to be included in the ouput CSS file should be included in https://github.com/appirio-tech/tc-ui/blob/feature/connectv2/src/styles/_tc-styles.scss which supposed to be included once per application.

**Comment by maxceem** [comment]
@vikasrohit this is fixed in this PR https://github.com/appirio-tech/tc-ui/pull/25

**Comment by maxceem** [comment]
@vikasrohit I think it's working as we've been using it for some time now, and no issues appeared.

**Comment by vikasrohit** [comment]
Great. Closing.
